excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Present-Perfect.github.io
title: Present Perfect
tagline: Learning to teach English
description: My awesome new site
paginate: 5